#ifndef myComDisplay
#define myComDisplay
#include "place.h"
#include "common.h"
#include "defs.h"
void tickclockT(void){}
void initmyDisplayT(void){}
void screenonT(void){}
void screenoffT(void){}
void showtimeT(void){}
#endif //myComDisplay